### ISSUE TITLE
Doesn't work with React.Fragment

### ISSUE THREAD

**Issue by RusinovAnton** [storybookjs/addon-jsx#34]
Hello

 I've tried to use `addon-jsx` for story that uses React.Fragment like this:
```
 .addWithJSX('bubble with components inside of it', () => (
    <Fragment>
      <MyComponent props />
      <MyComponent otherProps/>
    </Fragment>
  ));
``` 
and it fails with error:
```
Cannot convert a Symbol value to a string
    at exports.default (http://localhost:9001/static/preview.bundle.js:85619:17)
    at exports.default (http://localhost:9001/static/preview.bundle.js:81301:49)
    at exports.default (http://localhost:9001/static/preview.bundle.js:85518:39)
    at reactElementToJsxString (http://localhost:9001/static/preview.bundle.js:85494:35)
    at http://localhost:9001/static/preview.bundle.js:85400:50
    at mapSingleChildIntoContext (http://localhost:9001/static/preview.bundle.js:15121:26)
    at traverseAllChildrenImpl (http://localhost:9001/static/preview.bundle.js:14994:5)
    at traverseAllChildren (http://localhost:9001/static/preview.bundle.js:15065:10)
    at mapIntoWithKeyPrefixInternal (http://localhost:9001/static/preview.bundle.js:15141:3)
    at Object.mapChildren [as map] (http://localhost:9001/static/preview.bundle.js:15163:3)
``` 

It works perfectly once I replace `<Fragment>` with plain `<div>`

**Comment by sharvit** [comment]
I am facing the same issue with https://github.com/storybooks/storybook/tree/master/addons/info
This temporary solution/hack works for me:

```jsx
React.Fragment = ({ children }) => children;
React.Fragment.propTypes = {
  children: PropTypes.node.isRequired
};
React.Fragment.displayName = 'React.Fragment';
```

**Comment by tuchk4** [comment]
Faced this issue  in `5.0.3` with  these addons

```
addDecorator(addReadme);
addDecorator(withInfo);
```

- If use together -- `Cannot convert a Symbol value to a string`
- If use separately -- no errors.

**Comment by jasongilmour** [comment]
I also see this issue with the combination of React.Fragment and the withInfo addon in Storybook 5.0.6

**Comment by TomaszWaszczyk** [comment]
As I had the same issue I concluded that either we have `React.Fragment` without 'withInfo' or 'withInfo' with `<div>`.

**Comment by hipstersmoothie** [comment]
As this seems to be a problem in addon-info I suggest someone go fix the bug there. Gonna close this issue since it doesn't have anything to do with addon-jsx
